#!/usr/bin/env bash
set -euo pipefail

root="$(cd "$(dirname "$0")/.." && pwd)"
evidence="${BIGSYNC_ASSET_EVIDENCE_DIRECTORY:?Set a fresh absolute evidence directory}"
[[ "$evidence" = /* ]] || { echo 'Evidence directory must be absolute' >&2; exit 1; }
mkdir -p "$evidence"
finish() {
  local status=$?
  trap - EXIT
  if [[ -f "$root/Package.resolved" ]]; then
    cp "$root/Package.resolved" "$evidence/Package.resolved" || status=1
  fi
  if [[ -f "$root/.build/debug.yaml" ]]; then
    cp "$root/.build/debug.yaml" "$evidence/build-plan.yaml" || status=1
  fi
  printf '%s\n' "$status" > "$evidence/overall-status.txt"
  exit "$status"
}
trap finish EXIT
git -C "$root" rev-parse HEAD > "$evidence/source-commit.txt"
git -C "$root" ls-tree -r HEAD > "$evidence/source-tree.txt"
swift --version > "$evidence/swift-version.txt"
"$(dirname "$(command -v swift)")/clang" --version > "$evidence/swift-toolchain-clang-version.txt"
xcrun clang --version > "$evidence/apple-clang-version.txt"
xcrun --show-sdk-path > "$evidence/sdk-path.txt"
command -v xcsift > "$evidence/xcsift-path.txt"
# Compile Realm's C/C++ with the selected Xcode SDK's companion compiler.
# SwiftPM 6.2.1 supports CC as its explicit Clang compiler override. Its bundled
# Clang instead imports s2's entire autogenerated C++20 module map, including
# unused gflags-dependent headers that Realm's package does not supply.
export CC="$(xcrun -f clang)"
printf '%s\n' "$CC" > "$evidence/selected-clang-path.txt"
"$CC" --version > "$evidence/selected-clang-version.txt"

set +e
swift test --verbose --package-path "$root" --configuration debug \
  --filter 'BigSyncKitTests\.(HotfixCollectionSafetyTests|SyncRetainedRecordContractTests|SyncSplitOperationOwnershipTests|ChangeFeedMigrationResumeTests|SyncPhaseAttemptOwnershipTests)/' \
  --parallel --num-workers 1 --disable-swift-testing \
  --xunit-output "$evidence/native.junit.xml" 2>&1 | tee "$evidence/native.log" | xcsift
statuses=("${PIPESTATUS[@]}")
set -e
printf '%s\n' "${statuses[*]}" > "$evidence/pipeline-statuses.txt"
if [[ "${statuses[0]}" != 0 || "${statuses[1]}" != 0 || "${statuses[2]}" != 0 ]]; then
  exit 1
fi

python3 - "$root" "$evidence" <<'PY'
import json
import re
import sys
import xml.etree.ElementTree as ET
from collections import Counter
from pathlib import Path

root, evidence = map(Path, sys.argv[1:])
expected = Counter()
classes = ("HotfixCollectionSafetyTests", "SyncRetainedRecordContractTests",
           "SyncSplitOperationOwnershipTests", "ChangeFeedMigrationResumeTests",
           "SyncPhaseAttemptOwnershipTests")
for classname in classes:
    source = (root / "Tests/BigSyncKitTests" / (classname + ".swift")).read_text()
    # This inventories authored selectors for comparison to actual XCTest XML;
    # it does not assert on production implementation or replace discovery.
    source = re.sub(r'/\*[\s\S]*?\*/|//[^\n]*|"""[\s\S]*?"""|"(?:\\.|[^"\\])*"',
                    lambda match: " " * len(match.group()), source)
    for method in re.findall(r'\bfunc\s+(test\w+)\s*\(', source):
        expected[(classname, method)] += 1
assert expected and all(count == 1 for count in expected.values()), "Ambiguous authored roster"
(evidence / "expected-methods.json").write_text(json.dumps(sorted("/".join(key) for key in expected), indent=2) + "\n")

document = ET.parse(evidence / "native.junit.xml")
cases = list(document.iter("testcase"))
actual = Counter((case.attrib.get("classname", "").rsplit(".", 1)[-1],
                  case.attrib.get("name", "").removesuffix("()").rsplit("/", 1)[-1].rsplit(".", 1)[-1])
                 for case in cases)
assert actual == expected, {"missing": list((expected - actual).elements()), "unexpected": list((actual - expected).elements())}
assert not any(case.find(tag) is not None for case in cases for tag in ("failure", "error", "skipped")), "Native selection did not pass without skips"
assert all(int(suite.attrib.get(key, "0")) == 0 for suite in document.iter("testsuite") for key in ("errors", "failures", "skipped")), "JUnit aggregate failure or skip"
print(f"Passed all {len(cases)} authored native methods across {len(classes)} complete release-boundary classes")
PY
