#!/usr/bin/env bash
set -euo pipefail

root="$(cd "$(dirname "$0")/.." && pwd)"
evidence="${BIGSYNC_ASSET_EVIDENCE_DIRECTORY:?Set a fresh absolute evidence directory}"
[[ "$evidence" = /* ]] || { echo 'Evidence directory must be absolute' >&2; exit 1; }
mkdir -p "$evidence"
finish() {
  local status=$?
  trap - EXIT
  if [[ -f "$root/Package.resolved" ]]; then
    cp "$root/Package.resolved" "$evidence/Package.resolved" || status=1
  fi
  if [[ -f "$root/.build/debug.yaml" ]]; then
    cp "$root/.build/debug.yaml" "$evidence/build-plan.yaml" || status=1
  fi
  printf '%s\n' "$status" > "$evidence/overall-status.txt"
  exit "$status"
}
trap finish EXIT
git -C "$root" rev-parse HEAD > "$evidence/source-commit.txt"
git -C "$root" ls-tree -r HEAD > "$evidence/source-tree.txt"
swift --version > "$evidence/swift-version.txt"
"$(dirname "$(command -v swift)")/clang" --version > "$evidence/swift-toolchain-clang-version.txt"
xcrun clang --version > "$evidence/apple-clang-version.txt"
xcrun --show-sdk-path > "$evidence/sdk-path.txt"
command -v xcsift > "$evidence/xcsift-path.txt"
# Compile Realm's C/C++ with the selected Xcode SDK's companion compiler.
# SwiftPM 6.2.1 supports CC as its explicit Clang compiler override. Its bundled
# Clang instead imports s2's entire autogenerated C++20 module map, including
# unused gflags-dependent headers that Realm's package does not supply.
export CC="$(xcrun -f clang)"
printf '%s\n' "$CC" > "$evidence/selected-clang-path.txt"
"$CC" --version > "$evidence/selected-clang-version.txt"

python3 - "$root" "$evidence" <<'PY'
import json, re, sys
from collections import Counter
from pathlib import Path
root, evidence = map(Path, sys.argv[1:])
configuration = {'complete': ['HotfixCollectionSafetyTests', 'SyncRetainedRecordContractTests', 'SyncSplitOperationOwnershipTests', 'ChangeFeedMigrationResumeTests', 'SyncPhaseAttemptOwnershipTests'], 'focused': {'SyncUndoCloseoutW1Tests': {'source': 'SyncUndoCloseoutW1UploadSnapshotTests.swift', 'methods': ['testSemanticQuarantineIgnoresProvisionalInsertionAndRemoval', 'testSemanticQuarantineUsesCommittedFeedEpoch', 'testServerEvidenceIgnoresProvisionalAcknowledgement', 'testServerEvidenceIgnoresProvisionalRemovalAndForeignZoneReplacement', 'testServerEvidencePreservesExactAndCatalogStatePolicies', 'testServerEvidenceUsesCommittedAccountScopeAcrossSharedTargetRealm', 'testBootstrapServerEvidenceIgnoresProvisionalTrackingMembership']}, 'BigSyncKitTests': {'source': 'BigSyncKitTests.swift', 'methods': ['testInboundIdentityDeliveryIgnoresProvisionalInsert', 'testInboundIdentityDeliveryRetainsCommittedBatchDuringProvisionalChanges', 'testInboundSemanticQuarantineInspectionRetainsCommittedBlocker']}}}
expected = Counter()
def methods(source):
    # Authored selector accounting, not an assertion about production source.
    source = re.sub(r'(?P<raw>#+)(?:"""[\s\S]*?"""|"[\s\S]*?")(?P=raw)|/\*[\s\S]*?\*/|//[^\n]*|"""[\s\S]*?"""|"(?:\\.|[^"\\])*"',
                    lambda m: ' ' * len(m.group()), source)
    return Counter(re.findall(r'\bfunc\s+(test\w+)\s*\(', source))
for classname in configuration['complete']:
    source = root / 'Tests/BigSyncKitTests' / (classname + '.swift')
    authored = methods(source.read_text())
    assert authored and all(n == 1 for n in authored.values()), classname
    expected.update({(classname, method): 1 for method in authored})
for classname, selection in configuration['focused'].items():
    source = root / 'Tests/BigSyncKitTests' / selection['source']
    authored = methods(source.read_text())
    assert all(authored[method] == 1 for method in selection['methods']), classname
    expected.update({(classname, method): 1 for method in selection['methods']})
assert expected and all(n == 1 for n in expected.values()), 'Ambiguous native roster'
identities = sorted('BigSyncKitTests.' + classname + '/' + method for classname, method in expected)
(evidence / 'expected-methods.json').write_text(json.dumps(identities, indent=2) + '\n')
(evidence / 'selection-scope.json').write_text(json.dumps(configuration, indent=2) + '\n')
(evidence / 'native-filter.txt').write_text('^(?:' + '|'.join(re.escape(identity) for identity in identities) + ')$\n')
print(f'Requires {len(expected)} native methods: five complete classes and ten additional focused methods')
PY

set +e
swift test --package-path "$root" --configuration debug \
  --filter "$(cat "$evidence/native-filter.txt")" \
  --parallel --num-workers 1 --disable-swift-testing \
  --xunit-output "$evidence/native.junit.xml" 2>&1 | tee "$evidence/native.log" | xcsift
statuses=("${PIPESTATUS[@]}")
set -e
printf '%s\n' "${statuses[*]}" > "$evidence/pipeline-statuses.txt"
if [[ "${statuses[0]}" != 0 || "${statuses[1]}" != 0 || "${statuses[2]}" != 0 ]]; then
  exit 1
fi

python3 - "$evidence" <<'PY'
import json, sys
import xml.etree.ElementTree as ET
from collections import Counter
from pathlib import Path
evidence = Path(sys.argv[1])
expected = Counter(tuple(identity.removeprefix('BigSyncKitTests.').split('/'))
                   for identity in json.loads((evidence / 'expected-methods.json').read_text()))
document = ET.parse(evidence / 'native.junit.xml')
cases = list(document.iter('testcase'))
actual = Counter((case.attrib.get('classname', '').rsplit('.', 1)[-1],
                  case.attrib.get('name', '').removesuffix('()').rsplit('/', 1)[-1].rsplit('.', 1)[-1])
                 for case in cases)
assert actual == expected, {'missing': list((expected - actual).elements()), 'unexpected': list((actual - expected).elements())}
assert not any(case.find(tag) is not None for case in cases for tag in ('failure', 'error', 'skipped')), 'Native selection did not pass without skips'
assert all(int(suite.attrib.get(key, '0')) == 0 for suite in document.iter('testsuite') for key in ('errors', 'failures', 'skipped')), 'JUnit aggregate failure or skip'
summary = {'passed': len(cases), 'failed': 0, 'errors': 0, 'skipped': 0,
           'classes': dict(Counter(classname for classname, method in actual)),
           'scope': 'Five complete classes plus ten focused committed-evidence methods'}
(evidence / 'native-result-summary.json').write_text(json.dumps(summary, indent=2) + '\n')
print(json.dumps(summary))
PY
